# Values here will override previously loaded from settings.toml
# This file should be included in your `.gitignore` to never get exposed
# Dynaconf also offers the ability to read secrets from Vault server.

[default]
db__password = "Secret1234"

[development.db]
# using a special `dynaconf_merge` has the same effect as the `__` shorcut used above
dynaconf_merge = true
password = "NewSecret789"

# NOW go and read the `configs/.env` file
