site_name: {{ cookiecutter.project_name }}

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true

nav:
  - Getting started: getting-started.md
  - index.md
  - Code reference: reference.md